### ISSUE TITLE
Tests are failing!

### ISSUE THREAD

**Issue by Ivo-Evans** [fac-23/trip-planner#55]
I had a look at the `tests.js` file. When I changed `cy.visit("/my-documents");` to `cy.visit("http://localhost:3000/my-documents");`, the test passed :partying_face: To do this, the React dev server also needs to be running in the background

**Comment by OrianP** [comment]
Hi @millipede-cpu, 

I ran Cypress tests on my machine and got some helpful errors related to test syntax. See screenshots:

I think in this case, the issue is that we navigate to "/pagenotfound" but expect the url to include "singggle trip", I think it's just a matter of switching the two: so trying to navigate to a page that does not exist and checking that it contains test that says "Page not found". The url will contain whatever the user typed but the page content should show "Page not found".  


<img width="418" alt="Screenshot 2022-03-07 at 11 07 55" src="https://user-images.githubusercontent.com/77785778/157028731-76ae672b-f299-4ac0-a1a8-d638e2fc4170.png">

This one is just regarding the syntax of clicking a button in Cypress. You first need to select the button and then click it. 


<img width="405" alt="Screenshot 2022-03-07 at 11 07 14" src="https://user-images.githubusercontent.com/77785778/157029816-e814cccb-4833-4e9c-a697-c8a80d7ec6bf.png">
